environment: ${MICRONAUT_ENVIRONMENTS:local}
micronaut:
  application:
    name: coupon
  server:
    port: ${SERVER_PORT:8081}
    context-path: /coupon
    cors:
      enabled: true
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**s

http:
  client:
    read-timeout: 30s

netty:
  default:
    allocator:
      max-order: 3

datasources:
  default:
    url: jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: shivam
    password: void
    driverClassName: org.h2.Driver

h2:
  console:
    enabled: true

flyway:
  datasources:
    default:
      enabled: true

sentry:
  enabled: ${SENTRY_ENABLED:false}
  dsn: ${SENTRY_DSN:`https://45210f784ee745e18fdcaf7b3713bada@o435527.ingest.sentry.io/6474999`}
