DROP TABLE IF EXISTS COUPONCONFIGURATION;
DROP TABLE IF EXISTS USERCOUPONUSAGE;

CREATE TABLE COUPONCONFIGURATION(
  couponCode VARCHAR(100) PRIMARY KEY NOT NULL,
  globalTotalRepeatCount INT,
  userTotalRepeatCount INT,
  userDailyRepeatCount INT,
  userWeeklyRepeatCount INT
);
CREATE TABLE USERCOUPONUSAGE (
    id BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    userId VARCHAR(100) NOT NULL,
    couponCode VARCHAR(100) NOT NULL,
    usageDate DATE NOT NULL
);